server:
  port: 8002
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xxxx?useSSL=false&serverTimezone=UTC
    username: root
    password: xxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.zenith: debug
